name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install all dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: SSH Deploy to Hostinger
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}
            ARGS: "-azvc -i"
            SOURCE: "_site/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            REMOTE PORT: "65002"
            EXCLUDE: "/node_modules/, /resume/"